version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "relaylist-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ju7c2un44u5q"
s3_prefix = "relaylist-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
