AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  relaylist-api

  Sample SAM Template for relaylist-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  LoadStatsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: loadstats/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HourlyReload:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Name: load-relay-metrics
            Description: Load Relay Metrics
            Enabled: True

  APIViewRelays:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: viewrelays/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RelayListAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /relays
            Method: get

  RelayListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: relaylist
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true

  UpdateConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: LoadStatsFunction
      Destination:
        Id: RelayListTable
      Permissions:
        - Write
        - Read

  APIConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: APIViewRelays
      Destination:
        Id: RelayListTable
      Permissions:
        - Write
        - Read

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  APIViewRelays:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/relays/"
  LoadStatsFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LoadStatsFunction.Arn
  RelayListTable:
    Description: "DynamoDB Table"
    Value: !GetAtt RelayListTable.Arn
