AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  relaylist-api

  Sample SAM Template for relaylist-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 360
    MemorySize: 128

Resources:
  LoadStatsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: loadstats/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HourlyReload:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Name: load-relay-metrics
            Description: Load Relay Metrics
            Enabled: False
  
  ListRelaysFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: listrelays/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        HourlyReload:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
            Name: load-relay-metrics-ind
            Description: Load Relay Metrics
            Enabled: True

  LoadStatsFunctionInd:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: loadstatsind/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

  APIViewRelays:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: viewrelays/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        RelayListAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /relays
            Method: get

  RelayListTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: relaylist
      PrimaryKey:
        Name: name
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true

  UpdateConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: LoadStatsFunction
      Destination:
        Id: RelayListTable
      Permissions:
        - Write
        - Read

  ListRelaysConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: ListRelaysFunction
      Destination:
        Id: RelayListTable
      Permissions:
        - Read

  InvokeRelaysConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: ListRelaysFunction
      Destination:
        Id: LoadStatsFunctionInd
      Permissions:
        - Write

  LoadStatsFunctionIndConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: LoadStatsFunctionInd
      Destination:
        Id: RelayListTable
      Permissions:
        - Write
        - Read

  APIConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: APIViewRelays
      Destination:
        Id: RelayListTable
      Permissions:
        - Write
        - Read
